# Generated by Django 5.0.7 on 2024-08-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorphoto', models.ImageField(max_length=50, upload_to='')),
                ('doctorname', models.CharField(max_length=50)),
                ('doctoremail', models.CharField(max_length=50)),
                ('doctorphone', models.IntegerField(max_length=50)),
                ('doctorspecification', models.CharField(max_length=50)),
                ('doctorfees', models.CharField(max_length=50)),
            ],
        ),
    ]
