# Generated by Django 5.0.7 on 2024-08-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='doctorphoto',
            field=models.ImageField(upload_to=''),
        ),
    ]
